### ISSUE TITLE
error: unclosed string literal

### ISSUE THREAD

**Issue by bitsnaps** [imenebaraitame/RatpackDemo#2]
Salam,

The html content should goes into external files and not in java [code](https://github.com/imenebaraitame/RatpackDemo/blob/920a80d33eef1969f9700bbc8327ebfc813fd697/app/src/main/java/com/corposense/ocr/demo/App.java#L39).
I got the error `error: unclosed string literal` in gitpod.

**Comment by imenebaraitame** [comment]
Salam,

I know that it does'nt work in gitpod but it works in my machine, so to solve this issue I tried to create an external file (ratpack ->thymeleaf->uploadFile.html) and incorporate thymeleaf module to render a uploadFile.html template. but I got the error in my machine :

`Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @11531931`

**Comment by bitsnaps** [comment]
This #3 should fix it.
